name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64/v8]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and run Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ matrix.platform }}
        load: true
        push: false
        tags: user/app:latest

    - name: Run tests
      run: docker run user/app:latest
